### ISSUE TITLE
Extra page per profile

### ISSUE THREAD

**Issue by Tim-K93** [Tim-K93/capstone-project#13]

**Comment by Tim-K93** [comment]
## Value Proposition

As a User 
I want to click on certain profiles
so they get displayed on a new page

## Acceptance Criteria

- [ ] Profile shall be displayed on a new page
- [ ] Delete and edit button still have to work
      ​

## Tasks

- [ ] Create a new page
- [ ] Import code correctly so the buttons still work
      ​
