### ISSUE TITLE
Search filter bar

### ISSUE THREAD

**Issue by Tim-K93** [Tim-K93/capstone-project#15]

**Comment by Tim-K93** [comment]
## Value Proposition

As a User 
I want to have a filter search bar to choose between different species
So i can look for e.g dogs or cats in faster way
​

## Description



![Image](https://user-images.githubusercontent.com/122213586/228203369-8c148136-3d33-46d9-be59-dfe268db2b50.png)



## Acceptance Criteria

- [ ] Filter search bar shows the species you can choose
      ​

## Tasks

- [ ] Create input search field 
- [ ] Create new variable with useState
- [ ] Filter over species
      ​
