### ISSUE TITLE
Create Card

### ISSUE THREAD

**Issue by Tim-K93** [Tim-K93/capstone-project#4]

**Comment by Tim-K93** [comment]
## Value Proposition

As a User 
I want to create profiles about new animals in the shelter
so that they are added to the "All Cards" page


## Description

![Image](https://user-images.githubusercontent.com/122213586/224187384-e56d2bcb-3e2f-4cf5-9233-7b5b5aaceba5.png)
​

## Acceptance Criteria

- [ ] Error when a criteria (input) isn´t chosen (Please select option)
- [ ] Submit button has to function
- [ ] Inputs need to be saved in local storage

## Tasks

- [ ] Create form with inputs options to choose
- [ ] Create submit button
- [ ] Create error message
- [ ] Install local storage
- [ ] Routing to show navigation

      ​

**Comment by CTGitWhiz** [comment]
LGTM n1
