### ISSUE TITLE
Profile Card delete button

### ISSUE THREAD

**Issue by Tim-K93** [Tim-K93/capstone-project#8]

**Comment by Tim-K93** [comment]
## Value Proposition

As a User 
I want to be able to delete profile cards 
so you don´t see animals anymore as soon as they are adopted
​

## Description

![Image](https://user-images.githubusercontent.com/122213586/225293286-f797fe63-7aa1-4d97-a36d-d5c8e992d8c3.png)


## Acceptance Criteria

- [ ] show delete button
- [ ] profile should delete by pressing delete
      ​

## Tasks

- [ ] create delete button
- [ ] implement function to delete profiles
      ​
